In [ ]:
# import torch 
# import torch.nn as nn
# import torch.nn.functional as F


# class Swiglu(nn.Module): 
#     def __init__(self,in_features,hidden_features = None):
#         super().__init__()

#         hidden_features = hidden_features or in_features * 2 
#         self.Linear = nn.Linear(in_features, hidden_features * 2 )  

#     def forward(self,x):
#         score = self.Linear(x)
#         A, B = torch.chunk(score, 2 ,dim =-1)
#         return A * F.silu(B)
        


# #config
# batch_size = 4
# seq_len= 10 
# in_features = 34
# out_features = 64

# x = torch.randn(batch_size, seq_len, in_features)


# swiglu = Swiglu(in_features,out_features)
# output= swiglu(x)

# print(output.shape)

        



torch.Size([4, 10, 64])


In [ ]:
import torch 
import torch.nn as nn
import torch.nn.functional as F

### Building a Layer


In [ ]:
import torch 
import torch.nn as nn 
import torch.nn.functional as F


class Layer(nn.Module):
    def __init__(self, n_inputs,n_neuron, activation = None):
        super().__init__()

        self.weights = nn.Parameter (torch.randn(n_inputs, n_neuron))
        self.biases = nn.Parameter(torch.zeros(n_neuron))
        self.activation = activation


    def forward(self,x ):
        score = x @ self.weights  + self.biases
        if self.activation:
            return self.activation(score)
        else :
            return score
    
#config
n_inputs = 3
n_neuron = 5
batch_size = 2

myLayer = Layer(n_inputs,n_neuron,activation = F.relu)

for name, param in myLayer.named_parameters():
    print(f"Parameter '{name}' shape: {param.shape}")

x = torch.randn(batch_size,n_inputs)

prediction = myLayer(x)

print(f"Shape de la prédiction : {prediction.shape}") # Résultat : [2, 5]
print(prediction)
    

Parameter 'weights' shape: torch.Size([3, 5])
Parameter 'biases' shape: torch.Size([5])
Shape de la prédiction : torch.Size([9, 5])
tensor([[0.1669, 0.0000, 0.0000, 0.0000, 0.0000],
        [1.6586, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.1719, 0.0000, 1.4757, 0.0000],
        [0.1330, 0.0000, 1.0225, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.6976, 0.0000, 0.5732],
        [0.0000, 0.6619, 0.0000, 0.7374, 0.0000],
        [4.7451, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.4261, 0.0000, 2.7983, 0.0000],
        [3.2876, 0.0000, 0.0000, 0.4601, 0.2975]], grad_fn=<ReluBackward0>)


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class Layer(nn.Module):
    def __init__(self, n_inputs, n_neurons, activation=None):
        super().__init__() # Essential for all nn.Module classes

        # Create the weight matrix and bias vector.
        # By wrapping them in nn.Parameter, we tell PyTorch that these
        # are learnable parameters of the model.
        self.weights = nn.Parameter(torch.randn(n_inputs, n_neurons))
        self.biases = nn.Parameter(torch.zeros(n_neurons))

        # Store the activation function
        self.activation = activation

    def forward(self, x):
        # The linear step: x @ W + b
        score = x @ self.weights + self.biases

        # The activation step
        if self.activation:
            return self.activation(score)
        else:
            return score
# Configuration
n_inputs = 5
n_neurons = 3
batch_size = 2

# Create a layer with a ReLU activation
my_layer = Layer(n_inputs, n_neurons, activation=F.relu)

# Let's inspect its parameters (weights and biases)
# PyTorch automatically tracks them
for name, param in my_layer.named_parameters():
    print(f"Parameter '{name}' shape: {param.shape}")

# Create a batch of random input data
input_batch = torch.randn(batch_size, n_inputs)

print(f"\nInput batch shape: {input_batch.shape}")

# Perform the forward pass
output = my_layer.forward(input_batch)

print(f"Layer output shape: {output.shape}")
print(f"Layer output:\n{output}")

Practice 1: An Output Layer
Create a Layer instance that would be suitable as the output layer for a binary classification problem. It should take 16 inputs (from a previous hidden layer) and have a Sigmoid activation function. What should n_neurons be?



In [ ]:
#config
n_inputs = 16
n_neuron = 1
batch_size = 2




layer1 = Layer(n_inputs,n_neuron)
x = torch.randn(batch_size, n_inputs)
predict = layer1(x)

print(predict)

tensor([[-4.0018],
        [-1.8142]], grad_fn=<AddBackward0>)


Create a Layer instance that would be suitable as the output layer for a regression problem (like predicting a house price). It should take 8 inputs. What should n_neurons and activation be?



In [ ]:

n_inputs = 8
n_neuron = 1
batch_size = 2



layer2 = Layer(n_inputs,n_neuron)

x = torch.randn(batch_size, n_inputs)

predict = layer2(x)

print(predict)

tensor([[4.0671],
        [3.1124]], grad_fn=<AddBackward0>)


Practice 3: PyTorch's Built-in Layer
PyTorch already has a powerful, optimized class for this: nn.Linear. It works almost identically to our Layer class.



In [ ]:
# Our layer
layer1 = Layer(n_inputs=10, n_neurons=5)

# PyTorch's built-in equivalent
linear_layer = nn.Linear(in_features=10, out_features=5)

# Notice the parameters are named the same!
print("--- PyTorch nn.Linear Layer ---")
for name, param in linear_layer.named_parameters():
    print(f"Parameter '{name}' shape: {param.shape}")

Neural Network From Scratch: Implementing a Network


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# We'll use PyTorch's built-in nn.Linear for convenience,
# as it's equivalent to the Layer class we designed.
class SimpleNetwork(nn.Module):
    def __init__(self, n_inputs, n_hidden1, n_hidden2, n_outputs):
        super().__init__()

        # Define the layers
        self.hidden1 = nn.Linear(in_features=n_inputs, out_features=n_hidden1)
        self.hidden2 = nn.Linear(in_features=n_hidden1, out_features=n_hidden2)
        self.output = nn.Linear(in_features=n_hidden2, out_features=n_outputs)

    def forward(self, x):
        # This defines the data flow

        # Pass through first hidden layer, then apply ReLU
        x = self.hidden1(x)
        x = F.relu(x)

        # Pass through second hidden layer, then apply ReLU
        x = self.hidden2(x)
        x = F.relu(x)

        # Pass through output layer, then apply Sigmoid
        x = self.output(x)
        x = torch.sigmoid(x)

        return x

# Configuration
batch_size = 10
n_inputs = 3
n_hidden1 = 18
n_hidden2= 9 
n_outputs = 1


model = SimpleNetwork(n_inputs,n_hidden1,n_hidden2,n_outputs)

x = torch.randn(batch_size, n_inputs)

predict = model(x)

print(predict)

tensor([[0.5574],
        [0.5906],
        [0.5560],
        [0.5888],
        [0.5763],
        [0.5583],
        [0.5456],
        [0.5649],
        [0.5653],
        [0.5538]], grad_fn=<SigmoidBackward0>)


In [ ]:
import numpy as np

# Input: 3 words, each with a 4-dimensional embedding
seq_len = 3
d_model = 4
embeddings = np.array([
    [1, 0, 1, 0],  # Word 1
    [0, 1, 0, 1],  # Word 2
    [1, 1, 0, 0]   # Word 3
])

# The dimension for our Q, K, and V vectorsd_k = 3 
d_k = 3
# Weight matrices (initialized randomly)
W_Q = np.random.randn(d_model, d_k)
W_K = np.random.randn(d_model, d_k)
W_V = np.random.randn(d_model, d_k)

print("Embeddings shape:", embeddings.shape)
print("W_Q shape:", W_Q.shape)
print("W_K shape:", W_K.shape)
print("W_V shape:", W_V.shape)
# Compute Q, K, V matrices
Q = embeddings @ W_Q
K = embeddings @ W_K
V = embeddings @ W_V

print("\nQ matrix shape:", Q.shape)
print("K matrix shape:", K.shape)
print("V matrix shape:", V.shape)

# Step 1: Compute Q, K, V matrices
score = Q @ K.T
scaled_score = score / np.sqrt(d_model) * V 
print("\nRaw scores shape:", score.shape)
print("Scaled scores:")
print(scaled_score)


def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

aattention_weights = softmax(scaled_score)


print("\nAttention weights shape:", attention_weights.shape)
print("Attention weights (each row sums to 1):")
print(attention_weights)

output = np.dot(attention_weights,V)

print("\nOutput shape:", output.shape)
print("Final output of the attention layer:")
print(output)

Embeddings shape: (3, 4)
W_Q shape: (4, 3)
W_K shape: (4, 3)
W_V shape: (4, 3)

Q matrix shape: (3, 3)
K matrix shape: (3, 3)
V matrix shape: (3, 3)

Raw scores shape: (3, 3)
Scaled scores:
[[ 1.98962745 -0.66611328 -1.07333081]
 [-0.21256893 -0.054343    0.68178606]
 [ 0.24722263 -0.55432644  0.02024511]]
(3, 3)
[[0.89525837 0.06288902 0.04185261]
 [0.21658201 0.25371085 0.52970714]
 [0.44532081 0.19978581 0.35489338]]


In [ ]:
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

def self_attention(embeddings, d_k):
    d_model = embeddings.shape[1]
    
    # 1. Initialize weights and create Q, K, V
    W_Q = np.random.randn(d_model, d_k)
    W_K = np.random.randn(d_model, d_k)
    W_V = np.random.randn(d_model, d_k)
    Q = np.dot(embeddings, W_Q)
    K = np.dot(embeddings, W_K)
    V = np.dot(embeddings, W_V)
    
    # 2. Calculate and scale scores
    scores = np.dot(Q, K.T)
    scaled_scores = scores / np.sqrt(d_k)
    
    # 3. Softmax to get weights
    attention_weights = softmax(scaled_scores)
    
    # 4. Multiply weights by V
    output = np.dot(attention_weights, V)
    
    return output, attention_weights

# --- Example Usage ---
embeddings = np.array([[1,0,1,0], [0,1,0,1], [1,1,0,0]])
final_output, weights = self_attention(embeddings, d_k=3)

print("\n--- Final Function Output ---")
print("Final output:\n", final_output)
print("\nAttention weights:\n", weights)


--- Final Function Output ---
Final output:
 [[-0.56202136  0.11866705  1.38482586]
 [-0.51388457  0.68612124  0.06572029]
 [-0.49315622  0.62117127  0.41637597]]

Attention weights:
 [[0.01400844 0.97939623 0.00659533]
 [0.64231108 0.24894717 0.10874175]
 [0.42545036 0.37390669 0.20064295]]


In [9]:
import numpy as np 

seq_len = 3
d_model = 4
embeddings = np.array([
    [1,0,1,0],
    [1,1,0,0],
    [1,0,1,0],
])
d_k = 3

W_Q = np.random.randn(d_model,d_k)
W_K = np.random.randn(d_model,d_k)
W_V = np.random.randn(d_model,d_k)


print("Embeddings shape:", embeddings.shape)
print("W_Q shape:", W_Q.shape)
print("W_K shape:", W_K.shape)
print("W_V shape:", W_V.shape)

Q = np.dot(embeddings, W_Q)
K = np.dot(embeddings, W_K)
V = np.dot(embeddings, W_V)

#scaled our score 

score =np.dot(Q,K.T)

scaled_score = score / np.sqrt(d_K)

def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=-1, keepdims = True)

attention_weights = softmax(scaled_score)


print("\nAttention weights shape:", attention_weights.shape)
print("Attention weights (each row sums to 1):")
print(attention_weights)

output = np.dot(attention_weights,V)



Embeddings shape: (3, 4)
W_Q shape: (4, 3)
W_K shape: (4, 3)
W_V shape: (4, 3)

Attention weights shape: (3, 3)
Attention weights (each row sums to 1):
[[0.25067945 0.49864111 0.25067945]
 [0.3347664  0.3304672  0.3347664 ]
 [0.25067945 0.49864111 0.25067945]]


In [9]:
import numpy as np

seq_len = 3
d_model = 4
d_k = 3

embeddings = np.array([
    [1,0,1,0],
    [1,0,1,0],
    [1,0,1,0],
])


w_q = np.random.randn(d_model, d_k)
w_k = np.random.randn(d_model, d_k)
w_v = np.random.randn(d_model,d_k)

Q = np.dot(embeddings,w_q)
K = np.dot(embeddings, w_k)
V = np.dot(embeddings ,w_v)


score = np.dot(Q,K.T)

scaled_score = score/np.sqrt(d_k)

def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

attention_score = softmax(score)

output = np.dot(attention_score,V)
print(output)



[[ 0.24986219 -0.33198255  1.04507291]
 [ 0.24986219 -0.33198255  1.04507291]
 [ 0.24986219 -0.33198255  1.04507291]]


In [ ]:
import torch 
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F


class neuron(nn.Module):
    def __init__(self, n_inputs, hidden1,hidden2,n_output):
        super().__init__()

        self.hidden1 = nn.Linear(n_inputs,hidden1)
        self.hidden2 = nn.Linear(hidden1,hidden2)
        self.output = nn.Linear(hidden2 , n_output )

    def forward(self,x):
        x = F.relu(self.hidden1(x))
        x = F.relu(self.hidden2(x))
        x = self.output(x)

        return x 



n_inputs = 2
hidden1 = 4
hidden2 = 2
n_output = 1
batch_size = 10

model = neuron(n_inputs,hidden1,hidden2,n_output)

x = torch.randn(batch_size,n_inputs)

prediction = model(x)

print(prediction)
print(prediction.shape)


tensor([[-0.5463],
        [-0.5934],
        [-0.7405],
        [-0.5569],
        [-0.6277],
        [-0.6382],
        [-0.5503],
        [-0.6055],
        [-0.5195],
        [-0.6601]], grad_fn=<AddmmBackward0>)
torch.Size([10, 1])


### MoE

In [ ]:
import numpy as np

def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=-1, keepdims=True)

class Expert:
    # (Paste the Expert class from Part 1 here)
    def __init__(self, input_dim, hidden_dim):
        self.w1 = np.random.randn(input_dim, hidden_dim)
        self.w2 = np.random.randn(hidden_dim, input_dim)

    def forward(self, x):
        hidden = np.maximum(0, np.dot(x, self.w1))
        return np.dot(hidden, self.w2)

class MoELayer:
    def __init__(self, input_dim, hidden_dim, num_experts):
        self.num_experts = num_experts
        self.experts = [Expert(input_dim, hidden_dim) for _ in range(num_experts)]
        self.gate = np.random.randn(input_dim, num_experts)

    def forward(self, x):
        # 1. Get gating probabilities
        gating_logits = np.dot(x, self.gate)
        gating_weights = softmax(gating_logits)

        # 2. Select the best expert for each token (top-1)
        best_expert_indices = np.argmax(gating_weights, axis=1)

        # 3. Compute final output (loop for clarity)
        final_output = np.zeros_like(x)
        for i, token_input in enumerate(x):
            expert_idx = best_expert_indices[i]
            selected_expert = self.experts[expert_idx]
            expert_output = selected_expert.forward(token_input)
            final_output[i] = gating_weights[i, expert_idx] * expert_output
        
        return final_output

# --- Example Usage ---
# A batch of 4 tokens, each with dimension 10
input_data = np.random.randn(4, 10)

moe_layer = MoELayer(input_dim=10, hidden_dim=20, num_experts=8)
output = moe_layer.forward(input_data)

print("\n--- Final MoE Layer Output ---")
print("Output shape:", output.shape)
print("Final output for the batch:\n", output)

TypeError: MoELayer.__init__() got an unexpected keyword argument 'num_experts'

In [ ]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x))

class Expert:
    def __init__(self, input_dim, hidden_dim):
        #init des poids des experts 
        self.w1 = np.random.randn(input_dim,hidden_dim)
        self.w2 = np.random.randn(hidden_dim, input_dim)

    def forward(self,x):
        #forward de l'expert on applique relu sur w1 et ça ne retourne le score de W1 par w2
        hidden = np.argmax(0,np.dot(x,self.w1))
        return np.dot(hidden,self.w2)

#définition de la classe MoE
class MoE:
    def __init__(self, input_dim, hidden_dim,num_expert):
        self.num_expert = num_expert
        self.expert = [Expert(input_dim, hidden_dim) for _ in range(num_expert)]
        self.gate = np.random.randn(input_dim,num_expert)

    def forward(self,x):
    #on récupére les logits du produit input x le routeur pour avoir un vecteur par expert selon l'input
    gating_logits = np.dot(x,self.gate)
    gating_weights = softmax(gating_logits)

    #tok-1 selection d'expert sur chaque token 
    best_expert = np.argmax(gating_weights, axis=-1)
    #on remplit une matrice rempli de 0 qui sera remplie au fur et a mesure(?)
     final_output = np.zeros_like(x)
        ~#on crée une loop sur tout les expert et token input
        for i, token_input in enumerate(x):
            #selection du meilleur expert selon le token(i)
            expert_idx = best_expert_indices[i]
            #on met l'expert choisi dans une fonction selected expert qui va créer une matrice input_dim x hidden dim
            selected_expert = self.experts[expert_idx]
            #output de l'expert sur le forward de tout les token input qu'il recoivent
            expert_output = selected_expert.forward(token_input)
            #produit expert output x weights du gate(confiance) de l'expert pour nuancer les résultats
            final_output[i] = gating_weights[i, expert_idx] * expert_output
        #return du final output
        return final_output
    


IndentationError: expected an indented block after function definition on line 22 (3584676030.py, line 24)

### Implementation Du MLP de deepseek 





In [3]:

import torch
import torch.nn as nn
import torch.nn.functional as F

class DeepseekMLP(nn.Module):
    def __init__(self, dim: int, hidden_dim: int | None = None):
        super().__init__()

        # Ratio spécifique aux architectures Gated Linear Unit
        if hidden_dim is None: 
            hidden_dim = int(2.66 * dim)
        
        # On utilise bias=False car la Normalisation (RMSNorm) rend souvent les biais inutiles
        self.W1 = nn.Linear(dim, hidden_dim, bias=False)
        self.W2 = nn.Linear(dim, hidden_dim, bias=False)
        self.W3 = nn.Linear(hidden_dim, dim, bias=False)

    def forward(self, x):
       main_path = self.W1(x)

       gated_path = F.silu(self.W2(x))

       output = main_path * gated_path
       return output
if __name__ == '__main__':
    model_dim = 512
    mlp = DeepseekMLP(dim=model_dim)
    
    dummy_input = torch.randn(2, 10, model_dim)
    output = mlp(dummy_input)
    
    print(f"Input shape:  {dummy_input.shape}")
    print(f"Output shape: {output.shape}")

ModuleNotFoundError: No module named 'torch'

In [26]:

 

x = torch.randn(32,10,64)
print(x.shape)
x_reshape = x.view(-1, 64)
print(x_reshape.shape)


torch.Size([32, 10, 64])
torch.Size([320, 64])


In [32]:
q = torch.randn(8, 128, 512) # (Batch=8, Seq=128, Dim=512)
num_heads = 8 
head_dim = 512 // num_heads

q_split = q.view(8,128,num_heads, head_dim)
print(f"Shape après split : {q_split.shape}") # torch.Size([8, 128, 8, 64])

q_multihead  = q_split.transpose(1,2)
print(f"Shape finale : {q_multihead.shape}") # torch.Size([8, 8, 128, 64])


Shape après split : torch.Size([8, 128, 8, 64])
Shape finale : torch.Size([8, 8, 128, 64])


In [ ]:
a = torch.ones(4, 5) 
b = torch.ones(5)
print(a)
print(b)
print(a + b )

c = torch.ones(4)

result  =  a + 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1.])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])


In [33]:
# Tenseur de sortie de l'attention
out = torch.randn(2, 4, 10, 32) # (Batch=2, Heads=4, Seq=10, Head_dim=32)
# 1. On ramène la Séquence à sa place d'origine (on échange dim 1 et 2)
out_transposed = out.transpose(1, 2)
print(f"Shape après transpose : {out_transposed.shape}") # torch.Size([2, 10, 4, 32])
# 2. Le piège ! Si on fait .view() maintenant, PyTorch plante ou donne 
# un résultat mathématiquement faux car la mémoire a été mélangée par transpose().
# Il FAUT réorganiser la mémoire en un bloc continu d'abord.
out_contiguous = out_transposed.contiguous()
# 3. On "écrase" les têtes et leur dimension ensemble (4 * 32 = 128)
# Le -1 dit de calculer le total restant pour la dernière dimension
out_final = out_contiguous.view(2, 10, -1) 
print(f"Shape de sortie (Boss vaincu !) : {out_final.shape}") # torch.Size([2, 10, 128])


Shape après transpose : torch.Size([2, 10, 4, 32])
Shape de sortie (Boss vaincu !) : torch.Size([2, 10, 128])
